// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnzxmpqnjcuutbjatemc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduenhtcHFuamN1dXRiamF0ZW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Mjk4MDgsImV4cCI6MjA2NDIwNTgwOH0.eNEr-7kZhjWXMLw-n7dJqhgdXVyWcOXckERWQjeHJJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);